numT = int(input("Digite um número inteiro para ver sua tabuada: "))
num0 = int(numT*0)
num1 = int(numT*1)
num2 = int(numT*2)
num3 = int(numT*3)
num4 = int(numT*4)
num5 = int(numT*5)
num6 = int(numT*6)
num7 = int(numT*7)
num8 = int(numT*8)
num9 = int(numT*9)
num10 = int(numT*10)
print(f"A tabuada de {numT} é:")  
print("-------------------------------------------------------------------------------------")
print(f"{numT} X 1 = {num1}")   
print(f"{numT} X 2 = {num2}")
print(f"{numT} X 3 = {num3}")
print(f"{numT} X 4 = {num4}")
print(f"{numT} X 5 = {num5}")
print(f"{numT} X 6 = {num6}")
print(f"{numT} X 7 = {num7}")
print(f"{numT} X 8 = {num8}")
print(f"{numT} X 9 = {num9}")
print(f"{numT} X 10 = {num10}")
